/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import personagens.Heroi;
import personagens.Vilao;
import world_of_zuul.Luta;

/**
 *
 * @author Usuário
 */
public class Jogo extends javax.swing.JFrame {

    private Heroi h;
    private Vilao v;
    private Luta porrada;
    private DefaultTableModel model;
    private Connection con;
    private Statement st;
    private ResultSet rs;
    private Object[] rowData = new Object[4];
//    private final String SLT_ARMA = "SELECT id, ataque, defesa, agilidade, peso, equipado\n" +
//                                    "  FROM public.arma\n" +
//                                    " WHERE equipado = TRUE;";
    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();

        try {
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/jogo", "username", "password");
            st = con.createStatement();
            
            rs = st.executeQuery("SELECT name, level, xp, xp_max, attack, defense, life, setup FROM heroi" 
                               + " WHERE id = 1;");
            
            rs.next();
            
            String nome = rs.getString("name");
            int level = rs.getInt("level");
            int life = rs.getInt("life");
            int att = rs.getInt("attack");
            int def = rs.getInt("defense");
            int xp = rs.getInt("xp");
            int xp_max = rs.getInt("xp_max");
            long setup = rs.getInt("setup");
            
            h = new Heroi(nome, level, life, att, def, xp, xp_max, setup);
        
        } catch (SQLException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("bosta");
            h = new Heroi("", 1, 1, 1, 1, 1, 1, 1);
        }
        
        try{
            con = DriverManager.getConnection("jdbc:postgresql://localhost:5432/jogo", "username", "password");
            st = con.createStatement();
            model = (DefaultTableModel)itens.getModel();
            
            if(itens.getRowCount() == 0){
                rs = st.executeQuery("SELECT name, attack, defense, equipped FROM arma;");
                
                do{
                    rs.next();
                    
                    rowData[0] = rs.getString("name");
                    rowData[1] = rs.getInt("attack");
                    rowData[2] = rs.getInt("defense");   
                    rowData[3] = rs.getBoolean("equipped");
                    model.addRow(rowData);
                    
//                    if(rs.getBoolean("equipado")){
//                        h.setArmaIndice(itens.getRowCount() - 1);
//                    }
                }while(!rs.isAfterLast());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        lblEspada.setText((String)itens.getValueAt(h.getArmaIndice() -1, 0));
//        
        if(v == null){
            v = new Vilao("Monstro", 100, 10, 10);
        }
        
        h.setLife(100);
        v.setLife(100);
        
        //info heroi
        lblHeroi.setText(h.getName());
        pbVidaHeroi.setMaximum(h.getLife());
        pbVidaHeroi.setMinimum(0);
        pbVidaHeroi.setValue(h.getLife());
        lblVidaH.setText(String.valueOf(h.getLife()));
        
        //info vilao
        lblVilao.setText(v.getName());
        pbVidaVilao.setMaximum(v.getLife());
        pbVidaVilao.setMinimum(0);
        pbVidaVilao.setValue(v.getLife());
        lblVidaV.setText(String.valueOf(v.getLife()));
        
        porrada = new Luta(h, v);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeroi = new javax.swing.JLabel();
        btnLuta = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        pbVidaHeroi = new javax.swing.JProgressBar();
        lblVilao = new javax.swing.JLabel();
        pbVidaVilao = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        itens = new javax.swing.JTable();
        lblVidaH = new javax.swing.JLabel();
        lblVidaV = new javax.swing.JLabel();
        btnMochila = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblEspada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeroi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeroi.setToolTipText("");

        btnLuta.setText("Fight");
        btnLuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLutaActionPerformed(evt);
            }
        });

        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        itens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Ataque", "Defesa", "Agilidade", "Equipado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itens.setColumnSelectionAllowed(true);
        itens.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(itens);
        itens.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnMochila.setText("Inventario");
        btnMochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMochilaActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Itens Equipados");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblVidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEspada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pbVidaHeroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHeroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnLuta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMochila, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addComponent(lblVidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pbVidaVilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMochila)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHeroi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVilao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pbVidaHeroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pbVidaVilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblVidaH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVidaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEspada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btnLuta)
                        .addGap(212, 212, 212)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLutaActionPerformed
        porrada.pancadaria();
        
        pbVidaHeroi.setValue(h.getLife());
        pbVidaVilao.setValue(v.getLife());
        lblVidaH.setText(String.valueOf(h.getLife()));
        lblVidaV.setText(String.valueOf(v.getLife()));
        
        if(h.getLife() <= 0){
            btnLuta.setEnabled(false);
            return;
        }
        if(v.getLife() <= 0){
            btnLuta.setEnabled(false);
            return;
        }
    }//GEN-LAST:event_btnLutaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnLuta.setEnabled(true);
        
        h.setLife(100);
        v.setLife(100);
        
        lblHeroi.setText(h.getName());
        pbVidaHeroi.setValue(h.getLife());
        lblVidaH.setText(String.valueOf(h.getLife()));
        
        lblVilao.setText(v.getName());
        pbVidaVilao.setValue(v.getLife());
        lblVidaV.setText(String.valueOf(v.getLife()));
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnMochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMochilaActionPerformed
    }//GEN-LAST:event_btnMochilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
                //World_of_Zuul a = new World_of_Zuul();
                
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuta;
    private javax.swing.JButton btnMochila;
    private javax.swing.JButton btnStart;
    private javax.swing.JTable itens;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEspada;
    private javax.swing.JLabel lblHeroi;
    private javax.swing.JLabel lblVidaH;
    private javax.swing.JLabel lblVidaV;
    private javax.swing.JLabel lblVilao;
    private javax.swing.JProgressBar pbVidaHeroi;
    private javax.swing.JProgressBar pbVidaVilao;
    // End of variables declaration//GEN-END:variables
    
}
