/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import connect.Connect;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import personagens.Heroi;
import personagens.Vilao;
import world_of_zuul.Luta;

/**
 *
 * @author Usuário
 */
public class Jogo extends javax.swing.JFrame {

    private Heroi h;
    private Vilao v;
    private ArrayList<Vilao> horda;
    private Luta porrada;
    public static Connect c;
    /**
     * Creates new form Jogo
     */
    public Jogo(int id) {
        initComponents();
        c = new Connect();
        loadHeroi(id);
        loadVilao();
        
        //info heroi
        lblHeroi.setText(h.getName());
        pbVidaHeroi.setMaximum(h.getVidaAtual());
        pbVidaHeroi.setMinimum(0);
        pbVidaHeroi.setValue(h.getVidaAtual());
        lblVidaH.setText(String.valueOf(h.getLife()));
        lblLife.setText("LIFE:" + h.getLife());
        lblAtt.setText("ATT: " + h.getAttack());
        lblDef.setText("DEF: " + h.getDefense());
        
        //info vilao
        lblVilao.setText(v.getName());
        pbVidaVilao.setMaximum(v.getLife());
        pbVidaVilao.setMinimum(0);
        pbVidaVilao.setValue(v.getLife());
        lblVidaV.setText(String.valueOf(v.getLife()));
        
        porrada = new Luta(h, v);
        
    }

    private void loadHeroi(int id){
        try {
            
            ResultSet rs = c.getRS("SELECT name, level, xp, xp_max, attack, defense, life, setup, bag, gold FROM herois" 
                               + " WHERE id = " + id + ";");
            
            rs.next();
            
            String nome = rs.getString("name");
            int level = rs.getInt("level");
            int life = rs.getInt("life");
            int att = rs.getInt("attack");
            int def = rs.getInt("defense");
            int xp = rs.getInt("xp");
            int xp_max = rs.getInt("xp_max");
            long setup = rs.getInt("setup");
            long bag = rs.getInt("bag");
            int gold = rs.getInt("gold");
            
            System.out.println(xp);
            
            h = new Heroi(id ,nome, level, life, att, def, xp, xp_max, setup, bag, gold);
            
        } catch (SQLException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("erro load/jogo/heroi");
        }
    }
    
    private void loadVilao(){
        horda = new ArrayList<>();
        
        ResultSet rs = c.getRS("SELECT name, life, attack, defense FROM vilao;");
        try {
            rs.next();
            do{
                horda.add(new Vilao(rs.getString("name"), rs.getInt("life"), rs.getInt("attack"), rs.getInt("defense")));
                
                rs.next();
            }while(!rs.isAfterLast());
        } catch (SQLException ex) {
            Logger.getLogger(Jogo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        v = new Vilao(horda.get(0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeroi = new javax.swing.JLabel();
        btnLuta = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        pbVidaHeroi = new javax.swing.JProgressBar();
        lblVilao = new javax.swing.JLabel();
        pbVidaVilao = new javax.swing.JProgressBar();
        lblVidaH = new javax.swing.JLabel();
        lblVidaV = new javax.swing.JLabel();
        btnBag = new javax.swing.JButton();
        lblLife = new javax.swing.JLabel();
        lblAtt = new javax.swing.JLabel();
        lblDef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeroi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeroi.setToolTipText("");

        btnLuta.setText("Fight");
        btnLuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLutaActionPerformed(evt);
            }
        });

        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnBag.setText("Inventario");
        btnBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagActionPerformed(evt);
            }
        });

        lblLife.setText("LIFE: ");

        lblAtt.setText("ATT: ");

        lblDef.setText("DEF: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblVidaH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pbVidaHeroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHeroi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblLife)
                    .addComponent(lblAtt)
                    .addComponent(lblDef))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(lblVidaV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pbVidaVilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(lblLife))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBag)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAtt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDef)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHeroi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVilao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pbVidaHeroi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pbVidaVilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblVidaH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVidaV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLuta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLutaActionPerformed
        porrada.pancadaria();
        
        if(h.getVidaAtual() <= 0){
            btnLuta.setEnabled(false);
        }
        if(v.getLife() <= 0){
            int i = h.getLevel();
            h.increaseGold(v.getGold());
            h.increaseXp(v.getXp());
            if(i != h.getLevel()){
                new LevelUp(h, h.getLevel()-i).setVisible(true);
            }
            Random r = new Random();
            v = new Vilao(horda.get(r.nextInt(horda.size())));
            pbVidaVilao.setMaximum(v.getLife());
            porrada.setVilao(v);
            
        }
        
        reload();
    }//GEN-LAST:event_btnLutaActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        btnLuta.setEnabled(true);
        
        h.setVidaAtual(h.getLife());
        v.setLife(v.getVidaMax());
        
        pbVidaHeroi.setValue(h.getVidaAtual());
        lblVidaH.setText(String.valueOf(h.getLife()));
        
        pbVidaVilao.setValue(v.getLife());
        lblVidaV.setText(String.valueOf(v.getLife()));
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagActionPerformed
        Inventario i = new Inventario(h);
        i.setVisible(true);
    }//GEN-LAST:event_btnBagActionPerformed
    private void reload(){
        //info heroi
        lblHeroi.setText(h.getName());
        pbVidaHeroi.setValue(h.getVidaAtual());
        lblVidaH.setText(String.valueOf(h.getVidaAtual()));
        lblLife.setText("LIFE:" + h.getLife());
        lblAtt.setText("ATT: " + h.getAttack());
        lblDef.setText("DEF: " + h.getDefense());
        
        
        //info vilao
        lblVilao.setText(v.getName());
        pbVidaVilao.setValue(v.getLife());
        lblVidaV.setText(String.valueOf(v.getLife()));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Jogo().setVisible(true);
                
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBag;
    private javax.swing.JButton btnLuta;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblAtt;
    private javax.swing.JLabel lblDef;
    private javax.swing.JLabel lblHeroi;
    private javax.swing.JLabel lblLife;
    private javax.swing.JLabel lblVidaH;
    private javax.swing.JLabel lblVidaV;
    private javax.swing.JLabel lblVilao;
    private javax.swing.JProgressBar pbVidaHeroi;
    private javax.swing.JProgressBar pbVidaVilao;
    // End of variables declaration//GEN-END:variables
    
}
