/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import personagens.Heroi;

/**
 *
 * @author Usuario
 */
public class LevelUp extends javax.swing.JFrame {

    private Heroi h;
    private int i;
    private int ii;
    private int l;
    private int a;
    private int d;
    /**
     * Creates new form LevelUp
     */
    public LevelUp(Heroi h, int i) {
        initComponents();
        this.h = h;
        this.i = i;
        ii = i;
        l = 0;
        a = 0;
        d = 0;
        
        
        if(h.getLevel() % 10 == 0){
            h.setLife(h.getLife() + 20);
            h.setAttack(h.getAttack() + 10);
            h.setDefense(h.getDefense() + 10);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnMinusLife = new javax.swing.JButton();
        btnPlusLife = new javax.swing.JButton();
        btnMinusAtt = new javax.swing.JButton();
        btnPlusAtt = new javax.swing.JButton();
        btnMinusDef = new javax.swing.JButton();
        btnPlusDef = new javax.swing.JButton();
        btnLevelOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("    LIFE   ");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("ATTACK");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("DEFENSE");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnMinusLife.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMinusLife.setText("-");
        btnMinusLife.setEnabled(false);
        btnMinusLife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusLifeActionPerformed(evt);
            }
        });

        btnPlusLife.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPlusLife.setText("+");
        btnPlusLife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusLifeActionPerformed(evt);
            }
        });

        btnMinusAtt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMinusAtt.setText("-");
        btnMinusAtt.setEnabled(false);
        btnMinusAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusAttActionPerformed(evt);
            }
        });

        btnPlusAtt.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPlusAtt.setText("+");
        btnPlusAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusAttActionPerformed(evt);
            }
        });

        btnMinusDef.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMinusDef.setText("-");
        btnMinusDef.setEnabled(false);
        btnMinusDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusDefActionPerformed(evt);
            }
        });

        btnPlusDef.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPlusDef.setText("+");
        btnPlusDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusDefActionPerformed(evt);
            }
        });

        btnLevelOk.setText("OK");
        btnLevelOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLevelOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinusLife, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlusLife, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnLevelOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlusAtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinusAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlusDef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinusDef, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlusLife, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinusLife, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlusAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinusAtt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlusDef, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMinusDef, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLevelOk)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinusLifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusLifeActionPerformed
        // TODO add your handling code here:
        h.setLife(h.getLife() - 10);
        
        i++;
        l--;
        
        btnPlusLife.setEnabled(true);
        btnPlusAtt.setEnabled(true);
        btnPlusDef.setEnabled(true);
        
        if(l == 0){
            btnMinusLife.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinusLifeActionPerformed

    private void btnPlusLifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusLifeActionPerformed
        // TODO add your handling code here:
        h.setLife(h.getLife() + 10);
        
        i--;
        l++;
        
        btnMinusLife.setEnabled(true);
        
        if(i==0){
            btnPlusLife.setEnabled(false);
            btnPlusAtt.setEnabled(false);
            btnPlusDef.setEnabled(false);
        }
    }//GEN-LAST:event_btnPlusLifeActionPerformed

    private void btnMinusAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusAttActionPerformed
        // TODO add your handling code here:
        h.setAttack(h.getAttack() - 5);
        
        i++;
        a--;
        
        btnPlusLife.setEnabled(true);
        btnPlusAtt.setEnabled(true);
        btnPlusDef.setEnabled(true);
        
        if(a == 0){
            btnMinusAtt.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnMinusAttActionPerformed

    private void btnPlusAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusAttActionPerformed
        // TODO add your handling code here:
        h.setAttack(h.getAttack() + 5);
        
        i--;
        a++;
        
        btnMinusAtt.setEnabled(true);
        
        if(i==0){
            btnPlusLife.setEnabled(false);
            btnPlusAtt.setEnabled(false);
            btnPlusDef.setEnabled(false);
        }
    }//GEN-LAST:event_btnPlusAttActionPerformed

    private void btnMinusDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusDefActionPerformed
        // TODO add your handling code here:
        h.setDefense(h.getDefense() - 5);
        
        i++;
        d--;
        
        btnPlusLife.setEnabled(true);
        btnPlusAtt.setEnabled(true);
        btnPlusDef.setEnabled(true);
        
        if(d == 0){
            btnMinusDef.setEnabled(false);
        }
    }//GEN-LAST:event_btnMinusDefActionPerformed

    private void btnPlusDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusDefActionPerformed
        // TODO add your handling code here:
        h.setDefense(h.getDefense() + 5);
        
        i--;
        d++;
        
        btnMinusDef.setEnabled(true);
        
        if(i==0){
            btnPlusLife.setEnabled(false);
            btnPlusAtt.setEnabled(false);
            btnPlusDef.setEnabled(false);
        }
    }//GEN-LAST:event_btnPlusDefActionPerformed

    private void btnLevelOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLevelOkActionPerformed
        // TODO add your handling code here:
        if(ii == (l+a+d)){
            h.save();
            this.dispose();
        }
    }//GEN-LAST:event_btnLevelOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LevelUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLevelOk;
    private javax.swing.JButton btnMinusAtt;
    private javax.swing.JButton btnMinusDef;
    private javax.swing.JButton btnMinusLife;
    private javax.swing.JButton btnPlusAtt;
    private javax.swing.JButton btnPlusDef;
    private javax.swing.JButton btnPlusLife;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
